### ISSUE TITLE
jquery.get_selector test fails

### ISSUE THREAD

**Issue by simi** [polarblau/capycorder#13]
jquery.get_selector should return nth child selector.
Expected '.same:nth-child(2)' to equal '.inner > .same:nth-child(2)'.

```
Error: Expected '.same:nth-child(2)' to equal '.inner > .same:nth-child(2)'.
    at new <anonymous> (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:102:32)
    at [object Object].toEqual (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:1194:29)
    at [object Object].<anonymous> (http://localhost:4000/spec/lib/jquery_plugins/jquery.get_selector_spec.js:14:54)
    at [object Object].execute (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:1024:15)
    at [object Object].next_ (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:2025:31)
    at [object Object].start (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:1978:8)
    at [object Object].execute (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:2305:14)
    at [object Object].next_ (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:2025:31)
    at [object Object].start (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:1978:8)
    at [object Object].execute (http://localhost:4000/spec/jasmine/jasmine-1.2.0/jasmine.js:2450:14)
```

**Comment by polarblau** [comment]
The test might be at fault here.
